# Generated by Django 3.0.3 on 2020-03-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boxes',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
